### ISSUE TITLE
invoking cancelAirIncrement crashes game

### ISSUE THREAD

**Issue by 123hongte** [ToCraft/woodwalkers-mod#2]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelAirIncrement(Lnet/minecraft/world/entity/LivingEntity;I)V in walkers.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap walkers-common-refmap.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more

**Comment by 123hongte** [comment]
> Which Version did you use? (e.g. Mod-Version: 1.7 - MC-Version: 1.20.1 - Modloader: Fabric)

Mod 1.7, MC 1.20.1 Forge

**Comment by ToCraft** [comment]
How did you start the mod? With the Minecraft Launcher or something else?

**Comment by ToCraft** [comment]
issue will be closed in 5 days since I tried plenty o' things and never encounterd this issue.

**Comment by ToCraft** [comment]
Found some case, where this issue happens (in larger modpacks). I'll work on this now.

**Comment by ToCraft** [comment]
I'll try to finally fix it in 1.9

**Comment by ToCraft** [comment]
I could determinate it up to this: https://github.com/MinecraftForge/MinecraftForge/pull/9525 , and hoped, that this might fix it, but it didn't: https://github.com/MinecraftForge/MinecraftForge/pull/9680 . 
Maybe I'll find a workaround.

**Comment by ToCraft** [comment]
sadly didn't work with neoforged- I gotta wait for them.
