### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.LivingBreatheEvent

### ISSUE THREAD

**Issue by Sebedidep** [ToCraft/woodwalkers-mod#71]
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

newest version 

### CraftedCore version

newest version 

### Modloader version

47.1.3

### The latest.log file

attached 

### Issue description

Mod File: /F:/MinecraftCurseforge/Instances/Sebastian24443 Modpack/mods/walkers-3.0-forge.jar
	Failure message: Walkers (walkers) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingBreatheEvent
	Mod Version: 3.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.LivingBreatheEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.1-47.1.3.jar%23930!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.1-47.1.3.jar%23930!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.20.1-47.1.3.jar%23930!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23929!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

[crash-2024-03-05_15.22.32-fml.txt](https://github.com/ToCraft/woodwalkers-mod/files/14496683/crash-2024-03-05_15.22.32-fml.txt)

### Steps to reproduce

Minecraft wont start

**Comment by ToCraft** [comment]
Use Forge 47.2.0 ot newer. Forge basically reworked the breathing mechanism as of 47.2
